config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show]

  resources :topics do 
    resources :bookmarks, except: [:index]
  end 

  resources :bookmarks do
    resources :likes, only: [:create, :destroy]
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user

  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :likes, dependent: :destroy
  has_many :bookmarks # dependent destroy?

  def admin?
    role == 'admin'
  end 

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end 

  def liked_bookmarks
    Bookmark.find(likes.each {|l| l.bookmark_id})
  end

  def user_bookmarks
    bookmarks.includes(:topic)
  end

  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end 

  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end 
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @bookmark.topic = @topic

    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was saved."
      redirect_to @topic
    else 
      flash[:error] = "There was an error, please try again."
      render :new
    end 
  end 

  def edit
    
  end

  def update
  
  end 

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])

    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted!"
      redirect_to @topic
    else
      flash[:error] = "There was an error, please try again."
      render :show
    end 
  end 
    
  private 

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end 

  

  
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    @user = User.where(email: params['sender']).first
    if @user
      puts "we have user"
    else 
      puts "no user"
    end 

    @topic = Topic.where(title: params[:subject]).first_or_create # subject
    if @topic 
      puts "we have topic"
    else
      puts "no  topic"
    end 

    if @user
      puts "about to create bookmark"
     @bookmark = @topic.bookmarks.create(url: params['stripped-text'], user_id: @user.id) # body of email
    
    end 
    if @bookmark 
      puts "created bookmark #{@bookmark.url}" 
    else
      puts "no bookmark created"
    end 

    head 200 
  end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like
    if like.save
      flash[:notice] = "You like this bookmark!"
    else
      flash[:error] = "There was an error, please try again."
    end
    redirect_to @bookmark.topic
  end 

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    authorize like
    if like.destroy
      flash[:notice] = "You don't like this bookmark anymore."
    else
      flash[:error] = "There was an error, please try again."
    end 
    redirect_to @bookmark.topic
  end 
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic= Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to @topic
      flash[:notice] = "Topic was saved!"
    else
      flash[:error] = "There was an error, please try again."
      render :new
    end    
  end 

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "There was an error, please try again."
      render :edit
    end 
  end 

  def destroy
    @topic = Topic.find(params[:id])

    authorize @topic
    if @topic.destroy
      flash[:notice] = "Topic was deleted!"
    else
      flash[:error] = "There was an error, please try again."
    end
    redirect_to topics_path
  end 

  private

  def topic_params
    params.require(:topic).permit(:title)
  end 
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_bookmarks = current_user.user_bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end

  def update 
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated!"
      redirect_to edit_user_registration_path
    else 
      flash[:error] = "Invalid user information, please try again."
      redirect_to edit_user_registration_path
    end 
  end 

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="col-xs-6 col-md-3">
  <%= link_to '', bookmark.url, class: 'embedly-card' %>
  <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>    
  <% if policy(bookmark).destroy? %>
    <%= link_to "Delete Bookmark", [bookmark.topic, bookmark], method: :delete, class: 'btn btn-danger' %>
    <% end %>
</div>

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<div class="col-md-6 col-md-offset-3">
  <%= form_for [@topic, @bookmark] do |f| %>
    <div class="form-group">
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/bookmarks/show.html.haml
/ %h1= link_to @bookmark.url

/   = link_to "New Bookmark", new_topic_bookmark_path, class: 'btn btn-success'

app/views/incoming/edit.html.erb
<h1>Incoming#edit</h1>
<p>Find me in app/views/incoming/edit.html.erb</p>

app/views/incoming/index.html.erb
<h1>Incoming#index</h1>
<p>Find me in app/views/incoming/index.html.erb</p>

app/views/incoming/new.html.erb
<h1>Incoming#new</h1>
<p>Find me in app/views/incoming/new.html.erb</p>

app/views/incoming/show.html.erb
<h1>Incoming#show</h1>
<p>Find me in app/views/incoming/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>  <title>Jamarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags  %>
  <script src='//cdn.embedly.com/widgets/platform.js'></script>
</head>
<body>
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path  %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
    <div class="pull-right user-info">
      <% if current_user %>
      Hello <%= link_to (current_user.name || current_user.email), user_path(current_user) %>!
          <%= link_to "Edit", edit_user_registration_path %> || 
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
        
        <% end %>
      </div>
    </ul>
  </div>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger"</div>"
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning"</div>
      <button type="button" class="close" data-dismiss="alert" >&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
<%= yield  %>
</div> 
</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark, like], method: :delete do %>
        <i class="glyphicon glyphicon-heart"></i>
      <% end %>
    <% else %>
      <%= link_to [bookmark, Like.new], method: :post do %>
        <i class="glyphicon glyphicon-heart-empty"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= render 'topics/form' %>

app/views/topics/index.html.erb
<div class="container">
<h1>Jamarks</h1>
  <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  
    <div class="row">
      <% @topics.each do |topic| %>
        <%= render partial: 'users/topic', locals: {topic: topic, bookmarks: topic.bookmarks} %>
      <% end %>
    </div>


</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="form">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'topics/form' %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
<h1>Jamarks</h1>
  

  <h2><%= @topic.title %></h2>
    <% if policy(Bookmark.new).create? %>
      <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
    <% end %>
    <br>

  <% @topic.bookmarks.each do |bookmark| %>
    <div class="col-xs-6 col-md-3">
      <a class="embedly-card" href=<%= bookmark.url %> data-card-theme="light"></a>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>

    </div>
   
  <% end %>
</br>
</div>


    

app/views/users/_topic.html.erb
<%= content_tag_for :div, topic, class: 'row' do %>
  <div>
    <h3 class='text-center'>
      <%= link_to topic.title, topic_path(topic) %>
      <% if policy(topic).destroy? %>
        <%= link_to "Delete", topic, method: :delete, class: 'btn btn-danger' %>
      <% end %>
    </h3>

    <div class="container">
      <div class="span12 text-center">
        <%= render bookmarks %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1>My Bookmarks</h1>

      <% @user_bookmarks.group_by(&:topic).each do |topic, bookmarks| %>     
        <%= render partial: 'users/topic', locals: {topic: topic, bookmarks: bookmarks} %>
      <% end %>

  <h1>Liked Bookmarks</h1>

    <% @liked_bookmarks.group_by(&:topic).each do |topic, bookmarks| %>     
      <%= render partial: 'users/topic', locals: {topic: topic, bookmarks: bookmarks} %>
    <% end %>



</div>

app/views/welcome/about.html.erb
<h1>About Jamarks</h1></br>
<p class="about">Jamarks was re-created by Jamaleh Gyulay with the help of her mentor from <%= link_to "Bloc", "https://www.bloc.io" %>.</br>

It is a fun resource to collect and share favorite websites with friends.</br> 
With Jamarks you are able to view what others have bookmarked, </br>
save your "liked" bookmarks and ones that you have added yourself!</p></br>

<%= link_to "Follow me", "https://www.facebook.com/jamalehreneau", class: "social-btn" %> </br>

app/views/welcome/index.html.erb
<body id="image">
<div class="container">
  <div class="row">
    <div id="home-page">
    <h1 id="welcome">Jamarks</h1>
      <p id="intro">Use Jamarks to save and share your bookmarks!</p>
      <p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary'  %>
    or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
        today!
      </p>
    </div>
  </div>
</div>
</body>